services:
  security-tools:
    build: .
    ports:
      - "8080:8080"

  kali-toolbox:
    build:
      context: .
      dockerfile: Dockerfile.kali
    name: kali-toolbox
    tty: true
    stdin_open: true
