services:
  security-tools:
    build: .
    ports:
      - "8080:8080"
    # environment:
    #   - DB_HOST=database
    #   - DB_USER=admin
    #   - DB_PASSWORD=password
    #   - DB_NAME=auth-service
    # depends_on:
    #   database:
    #     condition: service_healthy
    # restart: unless-stopped

  nessus:
    image: tenable/nessus:latest-ubuntu
    environment:
      USERNAME: admin
      PASSWORD: password
    ports:
      - "8834:8834"

  zap:
    image: zaproxy/zap-stable
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=secret
    ports:
      - "8081:8080"

  kali-toolbox:
    build:
      context: .
      dockerfile: Dockerfile.kali
    tty: true
    stdin_open: true
